### ISSUE TITLE
Plugin doesn't work with Intellij 2016.2 Ultimate

### ISSUE THREAD

**Issue by zoehneto** [idok/sass-lint-plugin#12]
I have configured the plugin as shown below:
![image](https://cloud.githubusercontent.com/assets/8282547/18232181/7b3905b2-72ca-11e6-895c-698b200df795.png)

Because of the red bar at the bottom I assume there is an error, but I can't find anything in the log or the command line output. When I open a .scss file the plugin runs a node command (for example:
 `2016-09-04 18:05:11,749 [ 194813]   INFO -     #com.wix.nodejs.NodeRunner - Running node command: /usr/bin/node /home/zoehneto/IdeaProjects/tumblr-reader/node_modules/sass-lint/bin/sass-lint.js src/app/app.component.scss -v -q -c /home/zoehneto/IdeaProjects/tumblr-reader/.sass-lint.yml --format checkstyle`
) which does return issues (in this case: 
`<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="src/app/app.component.scss"><error line="14" column="26" severity="error" message="Color literals such as &apos;lightgrey&apos; should only be used in variable declarations (no-color-literals)" source="eslint.rules.no-color-literals" /><error line="21" column="10" severity="error" message="Color literals such as &apos;#6E6E6E&apos; should only be used in variable declarations (no-color-literals)" source="eslint.rules.no-color-literals" /></file></checkstyle>`
) but these errors don't show up in the editor window.

**Comment by huwdavidevans** [comment]
I don't get the red bar (IJ 2016.2.3) but it doesn't appear to be working for me, either.

**Comment by bharley** [comment]
I also don't get a red bar, but it doesn't appear to work in WebStorm 2016.2 or 2016.3.

**Comment by rokie83** [comment]
Same here

**Comment by PingusPepan** [comment]
I'm getting the red bar and it doesn't work for me on Phpstorm 2016.2.1 using version 1.0.5

**Comment by LarsHassler** [comment]
Same here in PhpStorm. No red bar in the settings, but it doesn't work. Not sure if the plugin runs, because i don't get any output in the logs from the plugin.

**System config:**
```
Mac OS X: 10.10.5
PhpStorm 2016.2.1
Build #PS-162.1889.1, built on August 23, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by stewartduffy** [comment]
Has anyone had this successfully working?

**Comment by loicsalou** [comment]
almost working in IntelliJ 2016.2.4 but sass-lint notifies problems by means of errors in event-log...
**my code** 
`$lightgray: #d1d1d1;`
`.active {`
`      background: $lightgray;`
`}
`

**errors**:
```
19:27	StreamException:  : only whitespace content allowed before start tag and not O (position: START_DOCUMENT seen O... @1:1) 

19:27	StreamException:  : only whitespace content allowed before start tag and not O (position: START_DOCUMENT seen O... @1:1) 
```

**Comment by scic** [comment]
I have the same empty red bar in IntelliJ 2016.1.5. It does not work.

**Comment by Daweo93** [comment]
Doesn't work on PHPStorm 2017.1. 
Is there any chance to make it works?

**Comment by idok** [comment]
fixed
