### ISSUE TITLE
changes to yml file is not applied until you disable/re-enable plugin

### ISSUE THREAD

**Issue by cuongluu8** [idok/sass-lint-plugin#17]
1. Error shown on scss file, e.g. indentation expect 2 got 4
2. change `.sass-lint.yml`, to turn indention rule off, e.g. `indentation: 0`
3. Error remains on scss file
4. Disable sass-lint plugin.  Apply.
5. Enable sass-lint plugin.  Apply.
6.  Error has gone from scss file

Is this expected behaviour? I would hope scss-lint.yml changes would be applied immediately.

**Comment by idok** [comment]
Doesn't reproduce
![sass-config-update](https://user-images.githubusercontent.com/1866543/31859337-019b5618-b713-11e7-80bc-a0d32bf7682d.gif)

**Comment by cuongluu8** [comment]
Just tried this again and it was still broken for me.  However checked the version of sass-lint I was using and it was 1.10.2.  When I upgraded to use the latest 1.12.1 it did work as you have pointed out.
Do you have any explanation on why the latest version of sass-lint can fix the plugin?

**Comment by idok** [comment]
maybe changes in the core code
