### ISSUE TITLE
Error gives balloon instead of highlight

### ISSUE THREAD

**Issue by fyodorvi** [idok/sass-lint-plugin#2]
We have strict linting rules on our project, they all are errors instead of warning, so pre-commit hook may fail on error. But plugin acts strange in this case: instead of highlighting errors it shows balloon with almost no information: "Error: 6 errors were detected in ...".

It doesn't make any sense.

**Comment by nikopavlica** [comment]
Same here. (Webstorm 11.0.3, sass-lint 1.5.0)

Although warnings are displayed as they should.

**Comment by rjaquino** [comment]
I modified my local copy of sass-lint.js to ignore the -q flag (and treat it as always enabled) and the sass-lint plugin worked for me. Passing through -q should work, given this experiment.

**Comment by chozilla** [comment]
We are now running two different rulesets to bypass this bug.
-**.sass-lint-dev.yml** has only warnings enabled and is used for development in webstorm.
-**.sass-lint.yml** has errors enabled for the build-process.

**Comment by nmcclay** [comment]
Yeah this is totally broken from my perspective.  I will just run with gulp if this is the expected behavior, the ESLint plugin should be the model of behavior this plugin follows by default: https://github.com/idok/eslint-plugin

**Comment by gitnik** [comment]
This plugin would be nothing short of amazing if worked the way everyone on here wants it to. Anything we can do to make this happen? I'm not exactly fluent in java but if someone is willing to point me into the right direction..

**Comment by mischkl** [comment]
Yep, same problem here

**Comment by szkrd** [comment]
Same here :(

**Comment by D34THWINGS** [comment]
Same problem here

**Comment by idok** [comment]
Looks like this is not relevant with latest version, please reopen if needed
