### ISSUE TITLE
works for .scss files but not for .sass files

### ISSUE THREAD

**Issue by googol7** [idok/sass-lint-plugin#5]
Created two files:

test.scss - here Sass Lint works properly
test.sass - here Sass Lint doesn't work

Please see the screenshots attached.

On the command line sass-lint.js reports the errors correctly for both files:

labor/test.sass
  2:13  warning  No unit allowed for values of 0                                            zero-unit
  2:24  warning  Color 'red' should be written in its hexadecimal form #ff0000              no-color-keywords
  2:24  warning  Color literals such as 'red' should only be used in variable declarations  no-color-literals
  2:28  warning  !important not allowed                                                     no-important
  3:1   warning  Indentation of 0, expected 2                                               indentation
  5:13  warning  No unit allowed for values of 0                                            zero-unit
  5:17  warning  !important not allowed                                                     no-important
  6:1   warning  Indentation of 0, expected 2                                               indentation

✖ 8 problems (0 errors, 8 warnings)

labor/test.scss
  2:5   warning  Indentation of 4, expected 2                                               indentation
  2:13  warning  No unit allowed for values of 0                                            zero-unit
  2:24  warning  Color 'red' should be written in its hexadecimal form #ff0000              no-color-keywords
  2:24  warning  Color literals such as 'red' should only be used in variable declarations  no-color-literals
  2:28  warning  !important not allowed                                                     no-important
  3:1   warning  Files must end with a new line                                             final-newline
![bildschirmfoto 2016-04-09 um 12 25 45](https://cloud.githubusercontent.com/assets/282412/14423981/e596f68a-ffde-11e5-9fcc-30f02d578c93.png)
![bildschirmfoto 2016-04-09 um 12 25 53](https://cloud.githubusercontent.com/assets/282412/14423982/e59766c4-ffde-11e5-95af-44da54002bf6.png)
![bildschirmfoto 2016-04-09 um 12 29 53](https://cloud.githubusercontent.com/assets/282412/14423983/e597b976-ffde-11e5-84ba-65cb923ff770.png)

✖ 6 problems (0 errors, 6 warnings)

**Comment by idok** [comment]
fixed
